openapi: "3.0.2"
info:
    title: Restaurant Business System API
    version: "1.0"
servers:
    - url: http://localhost:8080
      description: Local server
paths:
    /healthcheck:
        get:
            tags:
                - Healthcheck
            summary: Healthcheck
            description: Healthcheck
            responses:
                "200":
                    description: OK
    /account/register:
        post:
            tags:
                - Account
            summary: Register a new account
            description: Register a new account
            requestBody:
                content:
                    raw:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
            responses:
                "200":
                    description: OK
    /restaurant/create:
            post:
                tags:
                    - Restaurant
                summary: Create a new restaurant
                description: Create a new restaurant
                security:
                    - BasicAuth: [username:password]
                requestBody:
                    content:
                        raw:
                            schema:
                                type: object
                                properties:
                                    name:
                                        type: string
                responses:
                    "200":
                        description: OK
    /menu/create:
            post:
                tags:
                    - Menu
                summary: Create a new menu
                description: Create a new menu
                security:
                    - BasicAuth: [username:password]
                requestBody:
                    content:
                        raw:
                            schema:
                                type: object
                                properties:
                                    name:
                                        type: string
                                    idRestaurant:
                                        type: string
                responses:
                    "200":
                        description: OK
    /menu/get:
            get:
                tags:
                    - Menu
                summary: Get all menus from a restaurant
                description: Get all menus from a restaurant
                parameters:
                    - name: idRestaurant
                      in: query
                      required: true
                      schema:
                        type: string
                responses:
                    "200":
                        description: OK
    /food/create:
            post:
                tags:
                    - Food
                summary: Create a new food to a menu
                description: Create a new food to a menu
                security:
                    - BasicAuth: [abc:123]
                requestBody:
                    content:
                        raw:
                            schema:
                                type: object
                                properties:
                                    idMenu:
                                        type: string
                                    name:
                                        type: string
                                    price:
                                        type: number
                                    image:
                                        type: string
                responses:
                    "200":
                        description: OK
    /food/get:
            get:
                tags:
                    - Food
                summary: Get all foods from a menu
                description: Get all foods from a menu
                parameters:
                    - name: idMenu
                      in: query
                      required: true
                      schema:
                        type: string
                responses:
                    "200":
                        description: OK